const translations={
de:{
navSolutions:"Lösungen",networkTitle:"Netzwerk",serviceTitle:"Service",navSla:"SLA-Modelle",navContact:"Kontakt",
heroKicker:"Service & Support aus der Schweiz",heroTitle:"Verfügbarkeit, auf die Ihr Haus bauen kann.",heroText:"Wenn digitale Infrastruktur zum täglichen Betrieb gehört, braucht es mehr als eine Hotline: persönliche Verantwortung, Systemkenntnis und einen klaren Eskalationsweg.",heroCta:"SLA-Modelle vergleichen",heroCtaSecondary:"Service besprechen",heroStatus:"Persönlich erreichbar · strukturiert eskaliert",
benefitKicker:"Warum Hotelinnovativ",benefitTitle:"Nähe, die im Störungsfall zählt.",benefitLead:"Kurze Wege und ein Partner, der Ihre Lösung kennt, reduzieren Reibungsverluste — vom ersten Anruf bis zur dokumentierten Behebung.",benefitOneTitle:"Schweizer Ansprechpartner",benefitOneText:"Direkte Kommunikation, klare Zuständigkeit und persönliche Begleitung.",benefitTwoTitle:"Kenntnis Ihrer Systeme",benefitTwoText:"Support mit Kontext statt jedes Mal bei null zu beginnen.",benefitThreeTitle:"Remote zuerst",benefitThreeText:"Analyse und Fehlerbehebung beginnen schnell und ohne unnötige Anfahrt.",benefitFourTitle:"Passendes SLA",benefitFourText:"Basic für planbaren Bedarf oder 7/24 für hohe Verfügbarkeit.",
slaKicker:"Zwei Service-Level",slaTitle:"Der Support, der zu Ihrem Betrieb passt.",slaLead:"Wählen Sie die Abdeckung nach Betriebsmodell, interner Organisation und Verfügbarkeitsanforderung.",basicSchedule:"5 Tage × 10 Stunden",basicOne:"Support von Montag bis Freitag",basicTwo:"Telefonischer und technischer Support",basicThree:"Remote-Analyse und Fehlerbehebung",basicFour:"Unterstützung bei Sender- und Systemeinstellungen",basicFive:"Schweizer Ansprechpartner",basicFit:"Geeignet für Hotels mit eigener technischer Organisation oder überschaubarem Supportbedarf.",requestBasic:"Basic anfragen",premiumSchedule:"24 Stunden am Tag · 7 Tage die Woche",premiumOne:"Support rund um die Uhr",premiumTwo:"Wochenenden und Feiertage inklusive",premiumThree:"Schnelle Reaktionszeiten",premiumFour:"Eskalationsmanagement bei kritischen Störungen",premiumFive:"Lokaler Schweizer Ansprechpartner",premiumFit:"Geeignet für Hotels, Resorts, Kliniken und Betriebe mit hohen Anforderungen an Verfügbarkeit.",requestPremium:"7/24 anfragen",
processKicker:"Im Störungsfall",processTitle:"Direkt. Strukturiert. Nachvollziehbar.",processLead:"Ein klarer Ablauf verhindert, dass wertvolle Zeit zwischen Zuständigkeiten verloren geht.",processOneTitle:"Erreichen",processOneText:"Der Fall landet beim richtigen Ansprechpartner.",processTwoTitle:"Analysieren",processTwoText:"Remote-Diagnose und gezielte Fehlerbehebung.",processThreeTitle:"Eskalieren",processThreeText:"Kritische Fälle folgen einem klaren Eskalationsweg.",processFourTitle:"Dokumentieren",processFourText:"Lösung und nächste Schritte bleiben transparent.",
ctaKicker:"Service, der zu Ihnen passt",ctaTitle:"Sicher betreut.<br>Tag für Tag.",ctaText:"Wir helfen Ihnen, das passende Supportmodell für Ihr Haus und Ihre Infrastruktur festzulegen.",footerClaim:"Digitale Lösungen für moderne Hotelinfrastruktur.",imprint:"Impressum",privacy:"Datenschutz"
},
en:{
navSolutions:"Solutions",networkTitle:"Network",serviceTitle:"Service",navSla:"SLA models",navContact:"Contact",
heroKicker:"Service & support from Switzerland",heroTitle:"Availability your property can rely on.",heroText:"When digital infrastructure is part of daily operations, you need more than a hotline: personal responsibility, system knowledge and a clear escalation path.",heroCta:"Compare SLA models",heroCtaSecondary:"Discuss service",heroStatus:"Personally available · structured escalation",
benefitKicker:"Why Hotelinnovativ",benefitTitle:"Proximity that matters when issues arise.",benefitLead:"Short paths and a partner who knows your solution reduce friction — from the first call to documented resolution.",benefitOneTitle:"Swiss contact",benefitOneText:"Direct communication, clear responsibility and personal guidance.",benefitTwoTitle:"Knowledge of your systems",benefitTwoText:"Support with context instead of starting from zero every time.",benefitThreeTitle:"Remote first",benefitThreeText:"Analysis and troubleshooting begin quickly without unnecessary travel.",benefitFourTitle:"The right SLA",benefitFourText:"Basic for predictable needs or 7/24 for high availability.",
slaKicker:"Two service levels",slaTitle:"Support that fits your operations.",slaLead:"Choose coverage according to your operating model, internal organisation and availability requirements.",basicSchedule:"5 days × 10 hours",basicOne:"Support from Monday to Friday",basicTwo:"Telephone and technical support",basicThree:"Remote analysis and troubleshooting",basicFour:"Assistance with channel and system settings",basicFive:"Swiss contact",basicFit:"Suitable for hotels with their own technical organisation or manageable support needs.",requestBasic:"Request Basic",premiumSchedule:"24 hours a day · 7 days a week",premiumOne:"Support around the clock",premiumTwo:"Weekends and public holidays included",premiumThree:"Fast response times",premiumFour:"Escalation management for critical incidents",premiumFive:"Local Swiss contact",premiumFit:"Suitable for hotels, resorts, clinics and operations with high availability requirements.",requestPremium:"Request 7/24",
processKicker:"When an issue occurs",processTitle:"Direct. Structured. Traceable.",processLead:"A clear process prevents valuable time being lost between responsibilities.",processOneTitle:"Reach",processOneText:"The case reaches the right contact.",processTwoTitle:"Analyse",processTwoText:"Remote diagnosis and targeted troubleshooting.",processThreeTitle:"Escalate",processThreeText:"Critical cases follow a clear escalation path.",processFourTitle:"Document",processFourText:"The solution and next steps remain transparent.",
ctaKicker:"Service that fits",ctaTitle:"Safely supported.<br>Day after day.",ctaText:"We help you define the right support model for your property and infrastructure.",footerClaim:"Digital solutions for modern hotel infrastructure.",imprint:"Legal notice",privacy:"Privacy"
},
fr:{
navSolutions:"Solutions",networkTitle:"Réseau",serviceTitle:"Service",navSla:"Modèles SLA",navContact:"Contact",
heroKicker:"Service & support depuis la Suisse",heroTitle:"Une disponibilité sur laquelle votre établissement peut compter.",heroText:"Quand l’infrastructure digitale fait partie de l’exploitation quotidienne, il faut plus qu’une hotline : une responsabilité personnelle, la connaissance des systèmes et un chemin d’escalade clair.",heroCta:"Comparer les modèles SLA",heroCtaSecondary:"Parler du service",heroStatus:"Personnellement joignable · escalade structurée",
benefitKicker:"Pourquoi Hotelinnovativ",benefitTitle:"Une proximité décisive en cas d’incident.",benefitLead:"Des circuits courts et un partenaire qui connaît votre solution réduisent les frictions, du premier appel à la résolution documentée.",benefitOneTitle:"Interlocuteur suisse",benefitOneText:"Communication directe, responsabilités claires et accompagnement personnel.",benefitTwoTitle:"Connaissance de vos systèmes",benefitTwoText:"Un support avec contexte, sans repartir de zéro à chaque fois.",benefitThreeTitle:"Remote d’abord",benefitThreeText:"L’analyse et le dépannage commencent rapidement, sans déplacement inutile.",benefitFourTitle:"Le bon SLA",benefitFourText:"Basic pour un besoin planifiable ou 7/24 pour une haute disponibilité.",
slaKicker:"Deux niveaux de service",slaTitle:"Le support adapté à votre exploitation.",slaLead:"Choisissez la couverture selon votre modèle, votre organisation interne et vos exigences de disponibilité.",basicSchedule:"5 jours × 10 heures",basicOne:"Support du lundi au vendredi",basicTwo:"Support téléphonique et technique",basicThree:"Analyse à distance et dépannage",basicFour:"Aide aux réglages des chaînes et systèmes",basicFive:"Interlocuteur suisse",basicFit:"Adapté aux hôtels disposant d’une organisation technique interne ou de besoins de support modérés.",requestBasic:"Demander Basic",premiumSchedule:"24 heures sur 24 · 7 jours sur 7",premiumOne:"Support en continu",premiumTwo:"Week-ends et jours fériés inclus",premiumThree:"Temps de réaction rapides",premiumFour:"Gestion des escalades pour incidents critiques",premiumFive:"Interlocuteur suisse local",premiumFit:"Adapté aux hôtels, resorts, cliniques et établissements ayant de fortes exigences de disponibilité.",requestPremium:"Demander 7/24",
processKicker:"En cas d’incident",processTitle:"Direct. Structuré. Traçable.",processLead:"Un processus clair évite de perdre un temps précieux entre les responsabilités.",processOneTitle:"Joindre",processOneText:"Le cas arrive au bon interlocuteur.",processTwoTitle:"Analyser",processTwoText:"Diagnostic à distance et dépannage ciblé.",processThreeTitle:"Escalader",processThreeText:"Les cas critiques suivent un chemin d’escalade clair.",processFourTitle:"Documenter",processFourText:"La solution et les prochaines étapes restent transparentes.",
ctaKicker:"Un service adapté",ctaTitle:"Accompagné en sécurité.<br>Jour après jour.",ctaText:"Nous vous aidons à définir le modèle de support adapté à votre établissement et à son infrastructure.",footerClaim:"Solutions digitales pour une infrastructure hôtelière moderne.",imprint:"Mentions légales",privacy:"Protection des données"
},
it:{
navSolutions:"Soluzioni",networkTitle:"Rete",serviceTitle:"Service",navSla:"Modelli SLA",navContact:"Contatto",
heroKicker:"Service & support dalla Svizzera",heroTitle:"Disponibilità su cui la vostra struttura può contare.",heroText:"Quando l’infrastruttura digitale fa parte della gestione quotidiana serve più di una hotline: responsabilità personale, conoscenza dei sistemi e un percorso di escalation chiaro.",heroCta:"Confronta i modelli SLA",heroCtaSecondary:"Parliamo del service",heroStatus:"Contatto personale · escalation strutturata",
benefitKicker:"Perché Hotelinnovativ",benefitTitle:"Vicinanza che conta in caso di guasto.",benefitLead:"Percorsi brevi e un partner che conosce la soluzione riducono gli attriti, dalla prima chiamata alla risoluzione documentata.",benefitOneTitle:"Referente svizzero",benefitOneText:"Comunicazione diretta, responsabilità chiare e assistenza personale.",benefitTwoTitle:"Conoscenza dei sistemi",benefitTwoText:"Supporto con contesto, senza ripartire ogni volta da zero.",benefitThreeTitle:"Remote first",benefitThreeText:"Analisi e risoluzione iniziano rapidamente senza spostamenti inutili.",benefitFourTitle:"SLA adatto",benefitFourText:"Basic per esigenze pianificabili o 7/24 per alta disponibilità.",
slaKicker:"Due livelli di servizio",slaTitle:"Il supporto adatto alla vostra gestione.",slaLead:"Scegliete la copertura secondo il modello operativo, l’organizzazione interna e i requisiti di disponibilità.",basicSchedule:"5 giorni × 10 ore",basicOne:"Supporto dal lunedì al venerdì",basicTwo:"Supporto telefonico e tecnico",basicThree:"Analisi remota e risoluzione problemi",basicFour:"Assistenza per impostazioni di canali e sistemi",basicFive:"Referente svizzero",basicFit:"Adatto a hotel con organizzazione tecnica interna o esigenze di supporto contenute.",requestBasic:"Richiedi Basic",premiumSchedule:"24 ore al giorno · 7 giorni alla settimana",premiumOne:"Supporto continuo",premiumTwo:"Fine settimana e festività inclusi",premiumThree:"Tempi di reazione rapidi",premiumFour:"Gestione escalation per guasti critici",premiumFive:"Referente locale svizzero",premiumFit:"Adatto a hotel, resort, cliniche e strutture con elevate esigenze di disponibilità.",requestPremium:"Richiedi 7/24",
processKicker:"In caso di guasto",processTitle:"Diretto. Strutturato. Tracciabile.",processLead:"Un processo chiaro evita di perdere tempo prezioso tra le responsabilità.",processOneTitle:"Contattare",processOneText:"Il caso arriva al referente corretto.",processTwoTitle:"Analizzare",processTwoText:"Diagnosi remota e risoluzione mirata.",processThreeTitle:"Escalare",processThreeText:"I casi critici seguono un percorso chiaro.",processFourTitle:"Documentare",processFourText:"Soluzione e prossimi passi restano trasparenti.",
ctaKicker:"Service adatto a voi",ctaTitle:"Assistenza sicura.<br>Giorno dopo giorno.",ctaText:"Vi aiutiamo a definire il modello di supporto adatto alla struttura e all’infrastruttura.",footerClaim:"Soluzioni digitali per infrastrutture alberghiere moderne.",imprint:"Note legali",privacy:"Protezione dei dati"
}};
const languages=Object.keys(translations);
const languageButtons=document.querySelectorAll("[data-lang]");
function setLanguage(language){
 const lang=languages.includes(language)?language:"de";const dictionary=translations[lang];
 document.documentElement.lang=lang==="de"?"de-CH":lang;
 document.querySelectorAll("[data-i18n]").forEach(element=>{const value=dictionary[element.dataset.i18n];if(value)element.innerHTML=value});
 languageButtons.forEach(button=>button.classList.toggle("active",button.dataset.lang===lang));
 const url=new URL(location.href);url.searchParams.set("lang",lang);history.replaceState({},"",url);
 try{localStorage.setItem("hi-language",lang)}catch(e){}
}
languageButtons.forEach(button=>button.addEventListener("click",()=>setLanguage(button.dataset.lang)));
let stored="";try{stored=localStorage.getItem("hi-language")||""}catch(e){}
setLanguage(new URLSearchParams(location.search).get("lang")||stored||navigator.language.slice(0,2));
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("visible");revealObserver.unobserve(entry.target)}}),{threshold:.12});
document.querySelectorAll(".reveal").forEach(element=>revealObserver.observe(element));
function updateScrollState(){const scrollable=document.documentElement.scrollHeight-innerHeight;const progress=document.getElementById("progress");if(progress)progress.style.width=`${scrollable>0?scrollY/scrollable*100:0}%`;const header=document.getElementById("header");if(header)header.classList.toggle("scrolled",scrollY>40)}
addEventListener("scroll",updateScrollState,{passive:true});updateScrollState();
const year=document.getElementById("year");if(year)year.textContent=new Date().getFullYear();
const solutionsNavigation=document.querySelector(".nav-solutions");const solutionsTrigger=document.querySelector(".solutions-trigger");
if(solutionsNavigation&&solutionsTrigger){
 const closeSolutions=()=>{solutionsNavigation.classList.remove("open");solutionsTrigger.setAttribute("aria-expanded","false")};
 solutionsTrigger.addEventListener("click",event=>{event.stopPropagation();const isOpen=solutionsNavigation.classList.toggle("open");solutionsTrigger.setAttribute("aria-expanded",String(isOpen))});
 solutionsNavigation.querySelectorAll("a").forEach(link=>link.addEventListener("click",closeSolutions));
 document.addEventListener("click",event=>{if(!solutionsNavigation.contains(event.target))closeSolutions()});
 document.addEventListener("keydown",event=>{if(event.key==="Escape"){closeSolutions();solutionsTrigger.focus()}});
}
