const translations={
de:{
navSolutions:"Lösungen",navRelief:"Teamentlastung",navService:"Netzwerk & Service",navContact:"Kontakt",navHome:"Startseite",
heroEyebrow:"Digitale Hotelinfrastruktur aus der Schweiz",heroTitle:"Systeme, die Teams entlasten.<br>Erlebnisse, die Gäste begeistern.",heroLead:"Eine vernetzte Plattform für Entertainment, Guest Experience und Betrieb — persönlich geplant, sauber integriert und lokal betreut.",discoverWorlds:"Themenwelten entdecken",talkToUs:"Projekt besprechen",heroProof:"Swiss Service",
solutionsKicker:"Sechs Themen. Ein Partner.",solutionsTitle:"Ihre digitale Infrastruktur — klar verbunden.",solutionsLead:"Wählen Sie den Einstieg, der zu Ihrem Projekt passt. Dahinter steht immer ein System, das mit Ihrem Haus mitwächst.",
iptvText:"Interaktives Hotel-TV, Casting und digitale Services auf einem Bildschirm.",streamsTitle:"TV-Senderstreams",streamsText:"Internationale Senderpakete — flexibel, zentral und auf Ihren Gästemix abgestimmt.",journeyText:"Digitale Touchpoints von Pre-Stay bis After-Stay — nahtlos und im eigenen Look.",coaxText:"Bestehende Koaxialleitungen intelligent weiterverwenden — ohne unnötige Bauarbeiten.",networkTitle:"Netzwerk",networkText:"LAN, WLAN und segmentierte Netze als verlässliche Basis für den digitalen Hotelbetrieb.",serviceTitle:"Service",serviceText:"Beratung, Installation und Support mit persönlichen Ansprechpartnern in der Schweiz.",
reliefKicker:"Mehr Zeit für echte Gastfreundschaft",reliefTitle:"Wenn Fachkräfte knapp sind, sollte Technologie Routine übernehmen — nicht Nähe.",reliefText:"2026 zählt jede gute Arbeitsstunde. Vernetzte Systeme reduzieren manuelle Übergaben, automatisieren wiederkehrende Abläufe und geben Ihrem Team Raum für das, was kein System ersetzen kann: persönliche Aufmerksamkeit.",reliefCta:"Entlastungspotenzial besprechen",reliefOne:"Routine automatisieren",reliefOneText:"Informationen, Anfragen und wiederkehrende Touchpoints laufen strukturiert.",reliefTwo:"Prozesse verbinden",reliefTwoText:"TV, App, Netzwerk und Services greifen ineinander statt nebeneinander.",reliefThree:"Gäste persönlich begeistern",reliefThreeText:"Ihr Team gewinnt Zeit für Präsenz, Beratung und echte Gastgebermomente.",
promiseKicker:"Ein Partner in der Schweiz",promiseTitle:"Planen. Verbinden. Betreuen.",promiseText:"Kurze Wege, klare Verantwortung und Lösungen, die vom ersten Kabel bis zum letzten Gästetouchpoint zusammengedacht sind.",promiseLink:"Netzwerk & Service ansehen",contactKicker:"Ihr nächster Schritt",contactTitle:"Digitaler denken.<br>Gäste begeistern.",contactText:"Erzählen Sie uns, wo Ihr Hotel heute steht. Wir zeigen Ihnen den sinnvollsten nächsten Schritt.",contactCta:"Kontakt aufnehmen",footerClaim:"Digitale Lösungen für moderne Hotelinfrastruktur.",imprint:"Impressum",privacy:"Datenschutz",
serviceHeroKicker:"Netzwerk & Service",serviceHeroTitle:"Die Basis, die alles verbindet.",serviceHeroText:"Eine moderne Guest Journey beginnt nicht am Bildschirm, sondern in einer Infrastruktur, die zuverlässig funktioniert. Wir planen, integrieren und betreuen sie — mit einem verantwortlichen Partner in der Schweiz.",backHome:"Zur Übersicht",serviceMetaTwo:"Planung · Integration · Support",networkKicker:"Vernetzte Infrastruktur",networkHeroTitle:"Stabil für heute.<br>Bereit für morgen.",networkLead:"Wir betrachten das Netzwerk nicht isoliert. Es ist die gemeinsame Basis für IPTV, Guest WiFi, Mitarbeitende, mobile Services und künftige Automationen.",
lanTitle:"LAN & Switching",lanText:"Sauber geplante Verbindungen, passende Komponenten und eine dokumentierte Struktur für den täglichen Betrieb.",wifiTitle:"WLAN für Gäste und Betrieb",wifiText:"Durchdachte Abdeckung und ein konsistentes Erlebnis in Zimmern, öffentlichen Bereichen und Backoffice.",segmentTitle:"Getrennte digitale Bereiche",segmentText:"Gast-, Betriebs- und Gerätesysteme werden logisch strukturiert, damit Leistung und Übersicht erhalten bleiben.",coaxNetworkText:"Wo neue Leitungen unverhältnismässig wären, kann die vorhandene Koax-Infrastruktur zur modernen IP-Basis werden.",documentationTitle:"Dokumentation & Transparenz",documentationText:"Klare Übergaben und nachvollziehbare Unterlagen sorgen dafür, dass Ihre Infrastruktur beherrschbar bleibt.",
serviceKicker:"Ein Ansprechpartner. Drei Phasen.",lifecycleTitle:"Von der ersten Bestandsaufnahme bis zum stabilen Betrieb.",lifecycleLead:"Sie können bei jeder Phase einsteigen. Am stärksten ist die Lösung, wenn Planung, Umsetzung und Betreuung zusammengedacht werden.",checkTitle:"Analysieren",checkText:"Bestandsaufnahme vor Ort, Anforderungen klären, Engpässe sichtbar machen und einen realistischen Fahrplan definieren.",connectTitle:"Realisieren",connectText:"Projektierung, Konfiguration, koordinierte Installation, Inbetriebnahme und saubere Übergabe an Ihr Team.",careTitle:"Betreuen",careText:"Persönlicher Support, gezielte Optimierung und Weiterentwicklung, wenn Haus, Gäste oder Anforderungen wachsen.",
scopeKicker:"Was wir verbinden",scopeTitle:"Infrastruktur und Erlebnis aus einer Hand.",scopeLead:"Kein Sammelsurium einzelner Geräte, sondern ein verständliches Gesamtsystem mit klarer Verantwortung.",infraScopeTitle:"Infrastruktur",scopeSegmentation:"Netzwerksegmentierung",scopeDocumentation:"Dokumentation & Übergabe",experienceScopeTitle:"Digitale Gästeerlebnisse",scopeStreams:"Internationale TV-Senderstreams",scopeAutomation:"Schnittstellen & Automation",scopeNote:"Der genaue Leistungsumfang wird passend zu Gebäude, Bestand und Betriebsmodell zusammengestellt.",serviceCtaKicker:"Der sinnvolle nächste Schritt",serviceCtaTitle:"Erst verstehen.<br>Dann verbinden.",serviceCtaText:"Lassen Sie uns Ihre bestehende Infrastruktur und Ihre Ziele gemeinsam einordnen."
},
en:{
navSolutions:"Solutions",navRelief:"Team relief",navService:"Network & Service",navContact:"Contact",navHome:"Home",
heroEyebrow:"Digital hotel infrastructure from Switzerland",heroTitle:"Systems that support teams.<br>Experiences that delight guests.",heroLead:"One connected platform for entertainment, guest experience and operations — personally planned, cleanly integrated and locally supported.",discoverWorlds:"Explore solutions",talkToUs:"Discuss your project",heroProof:"Swiss service",
solutionsKicker:"Six topics. One partner.",solutionsTitle:"Your digital infrastructure — clearly connected.",solutionsLead:"Choose the entry point that fits your project. Behind it is a system designed to grow with your property.",
iptvText:"Interactive hotel TV, casting and digital services on one screen.",streamsTitle:"TV channel streams",streamsText:"International channel packages — flexible, central and tailored to your guest mix.",journeyText:"Digital touchpoints from pre-stay to after-stay — seamless and in your own look.",coaxText:"Reuse existing coax cabling intelligently — without unnecessary construction.",networkTitle:"Network",networkText:"LAN, WiFi and segmented networks as a dependable foundation for digital hotel operations.",serviceTitle:"Service",serviceText:"Consulting, installation and support with personal contacts in Switzerland.",
reliefKicker:"More time for genuine hospitality",reliefTitle:"When skilled people are scarce, technology should take over routine — not human connection.",reliefText:"In 2026, every productive hour matters. Connected systems reduce manual handovers, automate recurring processes and give your team room for what no system can replace: personal attention.",reliefCta:"Discuss relief potential",reliefOne:"Automate routine",reliefOneText:"Information, requests and recurring touchpoints follow a clear structure.",reliefTwo:"Connect processes",reliefTwoText:"TV, app, network and services work together instead of side by side.",reliefThree:"Delight guests personally",reliefThreeText:"Your team gains time for presence, advice and genuine moments of hospitality.",
promiseKicker:"One partner in Switzerland",promiseTitle:"Plan. Connect. Support.",promiseText:"Short paths, clear responsibility and solutions considered as one system — from the first cable to the final guest touchpoint.",promiseLink:"View Network & Service",contactKicker:"Your next step",contactTitle:"Think digitally.<br>Delight guests.",contactText:"Tell us where your hotel stands today. We will show you the most sensible next step.",contactCta:"Get in touch",footerClaim:"Digital solutions for modern hotel infrastructure.",imprint:"Legal notice",privacy:"Privacy",
serviceHeroKicker:"Network & Service",serviceHeroTitle:"The foundation that connects everything.",serviceHeroText:"A modern guest journey does not begin on a screen, but with infrastructure that works reliably. We plan, integrate and support it — with one responsible partner in Switzerland.",backHome:"Back to overview",serviceMetaTwo:"Planning · Integration · Support",networkKicker:"Connected infrastructure",networkHeroTitle:"Stable today.<br>Ready for tomorrow.",networkLead:"We do not view the network in isolation. It is the shared foundation for IPTV, guest WiFi, staff, mobile services and future automation.",
lanTitle:"LAN & switching",lanText:"Carefully planned connections, suitable components and a documented structure for daily operations.",wifiTitle:"WiFi for guests and operations",wifiText:"Thoughtful coverage and a consistent experience in rooms, public areas and back office.",segmentTitle:"Separated digital areas",segmentText:"Guest, operational and device systems are logically structured to preserve performance and clarity.",coaxNetworkText:"Where new cabling would be disproportionate, existing coax infrastructure can become a modern IP foundation.",documentationTitle:"Documentation & transparency",documentationText:"Clear handovers and understandable documentation keep your infrastructure manageable.",
serviceKicker:"One contact. Three phases.",lifecycleTitle:"From the first assessment to stable operations.",lifecycleLead:"You can enter at any phase. The solution is strongest when planning, implementation and support are considered together.",checkTitle:"Analyse",checkText:"On-site assessment, clarification of needs, visibility into bottlenecks and a realistic roadmap.",connectTitle:"Implement",connectText:"Project planning, configuration, coordinated installation, commissioning and a clean handover to your team.",careTitle:"Support",careText:"Personal support, targeted optimisation and further development as your property, guests or requirements grow.",
scopeKicker:"What we connect",scopeTitle:"Infrastructure and experience from one source.",scopeLead:"Not a collection of individual devices, but an understandable overall system with clear responsibility.",infraScopeTitle:"Infrastructure",scopeSegmentation:"Network segmentation",scopeDocumentation:"Documentation & handover",experienceScopeTitle:"Digital guest experiences",scopeStreams:"International TV channel streams",scopeAutomation:"Interfaces & automation",scopeNote:"The exact scope is tailored to your building, existing systems and operating model.",serviceCtaKicker:"The sensible next step",serviceCtaTitle:"Understand first.<br>Then connect.",serviceCtaText:"Let us assess your current infrastructure and goals together."
},
fr:{
navSolutions:"Solutions",navRelief:"Soutien aux équipes",navService:"Réseau & Service",navContact:"Contact",navHome:"Accueil",
heroEyebrow:"Infrastructure hôtelière digitale depuis la Suisse",heroTitle:"Des systèmes qui soulagent les équipes.<br>Des expériences qui enchantent les hôtes.",heroLead:"Une plateforme connectée pour le divertissement, l’expérience client et l’exploitation — planifiée personnellement, intégrée proprement et suivie localement.",discoverWorlds:"Découvrir les solutions",talkToUs:"Parler du projet",heroProof:"Service suisse",
solutionsKicker:"Six thèmes. Un partenaire.",solutionsTitle:"Votre infrastructure digitale — clairement connectée.",solutionsLead:"Choisissez l’entrée adaptée à votre projet. Derrière chaque thème se trouve un système qui évolue avec votre établissement.",
iptvText:"TV hôtelière interactive, casting et services digitaux sur un seul écran.",streamsTitle:"Flux de chaînes TV",streamsText:"Bouquets internationaux — flexibles, centralisés et adaptés à votre clientèle.",journeyText:"Des points de contact digitaux du pré-séjour à l’après-séjour — fluides et à votre image.",coaxText:"Réutiliser intelligemment le câblage coaxial existant — sans travaux inutiles.",networkTitle:"Réseau",networkText:"LAN, WiFi et réseaux segmentés comme base fiable de l’exploitation digitale.",serviceTitle:"Service",serviceText:"Conseil, installation et support avec des interlocuteurs personnels en Suisse.",
reliefKicker:"Plus de temps pour une hospitalité authentique",reliefTitle:"Quand les professionnels manquent, la technologie doit prendre en charge la routine — pas la proximité.",reliefText:"En 2026, chaque heure utile compte. Les systèmes connectés réduisent les transmissions manuelles, automatisent les tâches récurrentes et laissent à votre équipe du temps pour l’attention personnelle.",reliefCta:"Parler du potentiel d’allègement",reliefOne:"Automatiser la routine",reliefOneText:"Informations, demandes et points de contact récurrents suivent une structure claire.",reliefTwo:"Relier les processus",reliefTwoText:"TV, application, réseau et services travaillent ensemble.",reliefThree:"Enchanter personnellement les hôtes",reliefThreeText:"Votre équipe gagne du temps pour la présence, le conseil et l’accueil.",
promiseKicker:"Un partenaire en Suisse",promiseTitle:"Planifier. Connecter. Accompagner.",promiseText:"Des circuits courts, des responsabilités claires et des solutions pensées ensemble, du premier câble au dernier point de contact.",promiseLink:"Voir Réseau & Service",contactKicker:"Votre prochaine étape",contactTitle:"Penser digital.<br>Enchanter les hôtes.",contactText:"Dites-nous où se trouve votre hôtel aujourd’hui. Nous vous montrerons l’étape suivante la plus pertinente.",contactCta:"Nous contacter",footerClaim:"Solutions digitales pour une infrastructure hôtelière moderne.",imprint:"Mentions légales",privacy:"Protection des données",
serviceHeroKicker:"Réseau & Service",serviceHeroTitle:"La base qui relie tout.",serviceHeroText:"Un parcours client moderne ne commence pas sur un écran, mais par une infrastructure fiable. Nous la planifions, l’intégrons et l’accompagnons avec un partenaire responsable en Suisse.",backHome:"Retour à l’aperçu",serviceMetaTwo:"Planification · Intégration · Support",networkKicker:"Infrastructure connectée",networkHeroTitle:"Stable aujourd’hui.<br>Prête pour demain.",networkLead:"Le réseau est la base commune de l’IPTV, du WiFi invités, des collaborateurs, des services mobiles et des futures automatisations.",
lanTitle:"LAN & switching",lanText:"Connexions soigneusement planifiées, composants adaptés et structure documentée pour l’exploitation.",wifiTitle:"WiFi pour les hôtes et l’exploitation",wifiText:"Une couverture réfléchie et une expérience cohérente dans les chambres, espaces publics et back-office.",segmentTitle:"Espaces digitaux séparés",segmentText:"Les systèmes invités, opérationnels et techniques sont structurés pour préserver performance et visibilité.",coaxNetworkText:"Lorsque de nouveaux câbles seraient disproportionnés, l’infrastructure coaxiale existante peut devenir une base IP moderne.",documentationTitle:"Documentation & transparence",documentationText:"Des transmissions claires et des documents compréhensibles gardent l’infrastructure maîtrisable.",
serviceKicker:"Un interlocuteur. Trois phases.",lifecycleTitle:"Du premier état des lieux à une exploitation stable.",lifecycleLead:"Vous pouvez commencer à chaque phase. La solution est plus forte lorsque planification, réalisation et suivi sont pensés ensemble.",checkTitle:"Analyser",checkText:"État des lieux, clarification des besoins, identification des limites et feuille de route réaliste.",connectTitle:"Réaliser",connectText:"Conception, configuration, installation coordonnée, mise en service et transmission propre à votre équipe.",careTitle:"Accompagner",careText:"Support personnel, optimisation ciblée et évolution selon la croissance de votre établissement et de vos besoins.",
scopeKicker:"Ce que nous connectons",scopeTitle:"Infrastructure et expérience d’une seule main.",scopeLead:"Pas une collection d’appareils, mais un système global compréhensible avec des responsabilités claires.",infraScopeTitle:"Infrastructure",scopeSegmentation:"Segmentation du réseau",scopeDocumentation:"Documentation & transmission",experienceScopeTitle:"Expériences digitales",scopeStreams:"Flux de chaînes TV internationales",scopeAutomation:"Interfaces & automatisation",scopeNote:"Le périmètre exact est adapté au bâtiment, à l’existant et au modèle d’exploitation.",serviceCtaKicker:"La prochaine étape utile",serviceCtaTitle:"Comprendre d’abord.<br>Connecter ensuite.",serviceCtaText:"Évaluons ensemble votre infrastructure existante et vos objectifs."
},
it:{
navSolutions:"Soluzioni",navRelief:"Supporto al team",navService:"Rete & Service",navContact:"Contatto",navHome:"Home",
heroEyebrow:"Infrastruttura alberghiera digitale dalla Svizzera",heroTitle:"Sistemi che alleggeriscono il team.<br>Esperienze che entusiasmano gli ospiti.",heroLead:"Una piattaforma connessa per intrattenimento, guest experience e gestione — progettata personalmente, integrata con cura e seguita localmente.",discoverWorlds:"Scopri le soluzioni",talkToUs:"Parliamo del progetto",heroProof:"Servizio svizzero",
solutionsKicker:"Sei temi. Un partner.",solutionsTitle:"La vostra infrastruttura digitale — chiaramente connessa.",solutionsLead:"Scegliete il punto di partenza adatto al progetto. Dietro ogni tema c’è un sistema che cresce con la struttura.",
iptvText:"TV interattiva, casting e servizi digitali su un unico schermo.",streamsTitle:"Stream di canali TV",streamsText:"Pacchetti internazionali — flessibili, centralizzati e adatti ai vostri ospiti.",journeyText:"Touchpoint digitali dal pre-stay all’after-stay — fluidi e nel vostro stile.",coaxText:"Riutilizzare in modo intelligente i cavi coassiali esistenti — senza lavori inutili.",networkTitle:"Rete",networkText:"LAN, WiFi e reti segmentate come base affidabile per l’hotel digitale.",serviceTitle:"Service",serviceText:"Consulenza, installazione e supporto con referenti personali in Svizzera.",
reliefKicker:"Più tempo per la vera ospitalità",reliefTitle:"Quando il personale qualificato è limitato, la tecnologia deve assumere la routine — non la vicinanza.",reliefText:"Nel 2026 ogni ora produttiva conta. I sistemi connessi riducono i passaggi manuali, automatizzano le attività ricorrenti e lasciano al team spazio per l’attenzione personale.",reliefCta:"Parliamo del potenziale di alleggerimento",reliefOne:"Automatizzare la routine",reliefOneText:"Informazioni, richieste e touchpoint ricorrenti seguono una struttura chiara.",reliefTwo:"Collegare i processi",reliefTwoText:"TV, app, rete e servizi lavorano insieme.",reliefThree:"Entusiasmare personalmente gli ospiti",reliefThreeText:"Il team guadagna tempo per presenza, consulenza e vera ospitalità.",
promiseKicker:"Un partner in Svizzera",promiseTitle:"Pianificare. Collegare. Assistere.",promiseText:"Percorsi brevi, responsabilità chiare e soluzioni pensate insieme, dal primo cavo all’ultimo touchpoint.",promiseLink:"Scopri Rete & Service",contactKicker:"Il prossimo passo",contactTitle:"Pensare digitale.<br>Entusiasmare gli ospiti.",contactText:"Raccontateci dove si trova oggi il vostro hotel. Vi mostreremo il prossimo passo più sensato.",contactCta:"Contattaci",footerClaim:"Soluzioni digitali per infrastrutture alberghiere moderne.",imprint:"Note legali",privacy:"Protezione dei dati",
serviceHeroKicker:"Rete & Service",serviceHeroTitle:"La base che collega tutto.",serviceHeroText:"Una guest journey moderna non inizia dallo schermo, ma da un’infrastruttura affidabile. La progettiamo, integriamo e assistiamo con un partner responsabile in Svizzera.",backHome:"Torna alla panoramica",serviceMetaTwo:"Pianificazione · Integrazione · Supporto",networkKicker:"Infrastruttura connessa",networkHeroTitle:"Stabile oggi.<br>Pronta per domani.",networkLead:"La rete è la base comune per IPTV, Guest WiFi, collaboratori, servizi mobili e future automazioni.",
lanTitle:"LAN & switching",lanText:"Connessioni ben pianificate, componenti adatti e una struttura documentata per la gestione quotidiana.",wifiTitle:"WiFi per ospiti e gestione",wifiText:"Copertura studiata e un’esperienza coerente in camere, aree pubbliche e back office.",segmentTitle:"Aree digitali separate",segmentText:"I sistemi per ospiti, operazioni e dispositivi sono strutturati per mantenere prestazioni e chiarezza.",coaxNetworkText:"Dove nuovi cavi sarebbero sproporzionati, l’infrastruttura coassiale esistente può diventare una moderna base IP.",documentationTitle:"Documentazione & trasparenza",documentationText:"Consegne chiare e documenti comprensibili mantengono l’infrastruttura gestibile.",
serviceKicker:"Un referente. Tre fasi.",lifecycleTitle:"Dalla prima analisi alla gestione stabile.",lifecycleLead:"Potete iniziare da ogni fase. La soluzione è più forte quando progettazione, realizzazione e assistenza sono pensate insieme.",checkTitle:"Analizzare",checkText:"Analisi sul posto, chiarimento delle esigenze, individuazione dei limiti e roadmap realistica.",connectTitle:"Realizzare",connectText:"Progettazione, configurazione, installazione coordinata, messa in servizio e consegna al team.",careTitle:"Assistere",careText:"Supporto personale, ottimizzazione mirata ed evoluzione quando struttura, ospiti o requisiti crescono.",
scopeKicker:"Cosa colleghiamo",scopeTitle:"Infrastruttura ed esperienza da un’unica fonte.",scopeLead:"Non una raccolta di singoli dispositivi, ma un sistema complessivo comprensibile con responsabilità chiare.",infraScopeTitle:"Infrastruttura",scopeSegmentation:"Segmentazione della rete",scopeDocumentation:"Documentazione & consegna",experienceScopeTitle:"Esperienze digitali",scopeStreams:"Stream TV internazionali",scopeAutomation:"Interfacce & automazione",scopeNote:"L’ambito esatto viene adattato all’edificio, ai sistemi esistenti e al modello operativo.",serviceCtaKicker:"Il prossimo passo sensato",serviceCtaTitle:"Prima capire.<br>Poi collegare.",serviceCtaText:"Valutiamo insieme la vostra infrastruttura esistente e i vostri obiettivi."
}};
const languages=Object.keys(translations);
const languageButtons=document.querySelectorAll("[data-lang]");
function setLanguage(language){
  const lang=languages.includes(language)?language:"de";
  const dictionary=translations[lang];
  document.documentElement.lang=lang==="de"?"de-CH":lang;
  document.querySelectorAll("[data-i18n]").forEach(element=>{const value=dictionary[element.dataset.i18n];if(value)element.innerHTML=value});
  languageButtons.forEach(button=>button.classList.toggle("active",button.dataset.lang===lang));
  const url=new URL(window.location.href);url.searchParams.set("lang",lang);history.replaceState({},"",url);
  try{localStorage.setItem("hi-language",lang)}catch(e){}
}
languageButtons.forEach(button=>button.addEventListener("click",()=>setLanguage(button.dataset.lang)));
let stored="";try{stored=localStorage.getItem("hi-language")||""}catch(e){}
setLanguage(new URLSearchParams(location.search).get("lang")||stored||navigator.language.slice(0,2));
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("visible");revealObserver.unobserve(entry.target)}}),{threshold:.12});
document.querySelectorAll(".reveal").forEach(element=>revealObserver.observe(element));
function updateScrollState(){
  const scrollable=document.documentElement.scrollHeight-innerHeight;
  const progress=document.getElementById("progress");if(progress)progress.style.width=`${scrollable>0?scrollY/scrollable*100:0}%`;
  const header=document.getElementById("header");if(header)header.classList.toggle("scrolled",scrollY>40);
}
addEventListener("scroll",updateScrollState,{passive:true});updateScrollState();
const year=document.getElementById("year");if(year)year.textContent=new Date().getFullYear();
