const translations = {
  de: {
    navOverview: "Übersicht", navSolutions: "Lösungen", navPlatform: "Plattform", navContact: "Kontakt", contactCta: "Kontakt aufnehmen",
    heroEyebrow: "Digitale Lösungen für moderne Hotels", heroTitle: "Digitale Infrastruktur.<br>Gastfreundschaft neu gedacht.",
    heroLead: "Hotelinnovativ ist der Partner für digitale Lösungen für eine moderne Hotelinfrastruktur.", discoverWorlds: "Lösungen entdecken", talkToUs: "Mit uns sprechen", heroFootLeft: "Eine Plattform. Zwei Erlebniswelten.", scroll: "Scrollen",
    introKicker: "Das digitale Hotelerlebnis", introTitle: "Technologie, die im Hintergrund arbeitet. Wirkung, die der Gast spürt.", introText: "Vom ersten Kontakt bis zum Lieblingssender im Zimmer verbinden wir digitale Services, Entertainment und Infrastruktur zu einem konsistenten Erlebnis.",
    journeyKicker: "Guest Journey", journeyTitle: "Jeder Touchpoint.<br>Ein Erlebnis.", journeyText: "Eine digitale Gästereise, die vor der Ankunft beginnt, den Aufenthalt vereinfacht und nach der Abreise in Erinnerung bleibt.", journeyFeature1: "Pre-Arrival & Upselling", journeyFeature2: "Mobile Key & Guest App", journeyFeature3: "Check-out & Loyalty", openJourney: "Guest Journey erleben",
    streamsKicker: "TV-Streams", streamsTitle: "Die Welt zu Gast.<br>Auf jedem Bildschirm.", streamsText: "Internationale TV-Unterhaltung über IP – flexibel, zentral verwaltet und abgestimmt auf Ihren Gästemix.", streamsFeature1: "250+ internationale Sender", streamsFeature2: "Flexible Senderpakete", streamsFeature3: "Schweizer Support", openStreams: "TV-Streams entdecken", tvWelcome: "Ihre Welt.<br>Ihr Programm.",
    platformKicker: "Vernetzte Hotelinfrastruktur", platformTitle: "Ein Partner.<br>Ein digitales Ökosystem.", platformText: "Wir denken nicht in Einzelprodukten, sondern in Lösungen, die zusammenarbeiten.", ecosystemCore: "DIGITAL CORE", ecoGuestApp: "Guest App", ecoAutomation: "Automation",
    serviceKicker: "Service & Support", serviceTitle: "Lokal verankert.<br>Persönlich begleitet.", serviceLead: "Von der ersten Idee bis zum laufenden Betrieb bleibt Hotelinnovativ an Ihrer Seite – mit kurzen Wegen, direkter Verantwortung und einem Team in der Schweiz.", swissLabel: "Ihr Schweizer Technologiepartner", swissPromise: "Nah, schnell und zuverlässig.", swissText: "Persönliche Ansprechpartner in Baar, fundierte Projektbegleitung und Support, der Ihre Infrastruktur kennt.", serviceConsulting: "Beratung & Konzeption", serviceConsultingText: "Wir übersetzen Anforderungen in eine klare, zukunftsfähige Lösung – abgestimmt auf Haus, Gäste und Betrieb.", serviceIntegration: "Integration & Inbetriebnahme", serviceIntegrationText: "Saubere Planung, koordinierte Installation und verlässliche Integration in die bestehende Infrastruktur.", serviceSupport: "Support & Weiterentwicklung", serviceSupportText: "Direkte Hilfe, kurze Reaktionswege und kontinuierliche Optimierung über den gesamten Lebenszyklus.",
    audienceKicker: "Unsere Branchen", audienceTitle: "Digitale Erlebnisse für Hotels und Gesundheitseinrichtungen.", audienceLead: "Wo Menschen ankommen, bleiben und sich gut aufgehoben fühlen sollen, schafft Hotelinnovativ die digitale Verbindung.", sectorHotelLabel: "Hotellerie", sectorHotelTitle: "Mehr Komfort für Gäste.<br>Mehr Wirkung für Hotels.", sectorHotelText: "Guest Journey, IPTV, Casting, WiFi und Automation verbinden sich zu einem konsistenten Aufenthalt und effizienteren Abläufen.", sectorHotelLink: "Lösungen für Hotels", sectorHealthLabel: "Gesundheitseinrichtungen", sectorHealthTitle: "Interaktives Patienten-TV.<br>Information, Komfort und Verbindung.", sectorHealthText: "Das bestehende TV wird zur zentralen Kommunikationsplattform: Es informiert, unterhält und stärkt Patienten – während digitale Abläufe das Pflegepersonal entlasten.", healthFeature1: "TV & Unterhaltung", healthFeature2: "Information & Bildung", healthFeature3: "Essen & Service", healthFeature4: "Zimmersteuerung", healthFeature5: "Telehealth & Familie", healthFeature6: "Feedback & Kommunikation", sectorHealthLink: "Lösungen für Gesundheit",
    contactKicker: "Der nächste Schritt", contactTitle: "Digitaler denken.<br>Gäste begeistern.", contactText: "Lassen Sie uns über Ihre Infrastruktur, Ihre Gäste und Ihre Ziele sprechen.", footerClaim: "Ihr Partner für digitale Hotelinfrastruktur.", footerSolutions: "Lösungen", footerContact: "Kontakt", footerLegal: "Rechtliches", rights: "Alle Rechte vorbehalten.", footerTagline: "Proud to serve you.", backTop: "Nach oben", imprint: "Impressum", privacy: "Datenschutz", cookies: "Cookie-Richtlinie"
  },
  en: {
    navOverview: "Overview", navSolutions: "Solutions", navPlatform: "Platform", navContact: "Contact", contactCta: "Get in touch",
    heroEyebrow: "Digital solutions for modern hotels", heroTitle: "Digital infrastructure.<br>Hospitality reimagined.",
    heroLead: "Hotelinnovativ is your partner for digital solutions and modern hotel infrastructure.", discoverWorlds: "Discover solutions", talkToUs: "Talk to us", heroFootLeft: "One platform. Two experience worlds.", scroll: "Scroll",
    introKicker: "The digital hotel experience", introTitle: "Technology working in the background. Impact felt by every guest.", introText: "From the first touchpoint to a guest’s favourite channel, we connect digital services, entertainment and infrastructure into one consistent experience.",
    journeyKicker: "Guest Journey", journeyTitle: "Every touchpoint.<br>One experience.", journeyText: "A digital guest journey that begins before arrival, simplifies the stay and remains memorable long after departure.", journeyFeature1: "Pre-arrival & upselling", journeyFeature2: "Mobile Key & Guest App", journeyFeature3: "Check-out & loyalty", openJourney: "Experience the Guest Journey",
    streamsKicker: "TV Streams", streamsTitle: "The world as your guest.<br>On every screen.", streamsText: "International TV entertainment over IP – flexible, centrally managed and tailored to your guest mix.", streamsFeature1: "250+ international channels", streamsFeature2: "Flexible channel packages", streamsFeature3: "Swiss support", openStreams: "Discover TV Streams", tvWelcome: "Your world.<br>Your programme.",
    platformKicker: "Connected hotel infrastructure", platformTitle: "One partner.<br>One digital ecosystem.", platformText: "We do not think in isolated products, but in solutions designed to work together.", ecosystemCore: "DIGITAL CORE", ecoGuestApp: "Guest App", ecoAutomation: "Automation",
    serviceKicker: "Service & Support", serviceTitle: "Locally rooted.<br>Personally supported.", serviceLead: "From the first idea to daily operations, Hotelinnovativ stays by your side – with short paths, direct responsibility and a team in Switzerland.", swissLabel: "Your Swiss technology partner", swissPromise: "Close, fast and reliable.", swissText: "Personal contacts in Baar, experienced project guidance and support that knows your infrastructure.", serviceConsulting: "Consulting & concept", serviceConsultingText: "We turn requirements into a clear, future-ready solution tailored to your property, guests and operations.", serviceIntegration: "Integration & commissioning", serviceIntegrationText: "Clean planning, coordinated installation and reliable integration with your existing infrastructure.", serviceSupport: "Support & development", serviceSupportText: "Direct assistance, short response paths and continuous optimisation throughout the entire lifecycle.",
    audienceKicker: "Our industries", audienceTitle: "Digital experiences for hotels and healthcare facilities.", audienceLead: "Where people arrive, stay and need to feel well cared for, Hotelinnovativ creates the digital connection.", sectorHotelLabel: "Hospitality", sectorHotelTitle: "More comfort for guests.<br>More impact for hotels.", sectorHotelText: "Guest Journey, IPTV, casting, WiFi and automation combine to create a consistent stay and more efficient operations.", sectorHotelLink: "Solutions for hotels", sectorHealthLabel: "Healthcare facilities", sectorHealthTitle: "Interactive patient TV.<br>Information, comfort and connection.", sectorHealthText: "Existing TV infrastructure becomes a central communication platform that informs, entertains and empowers patients while digital workflows support care teams.", healthFeature1: "TV & entertainment", healthFeature2: "Information & education", healthFeature3: "Meals & services", healthFeature4: "Room controls", healthFeature5: "Telehealth & family", healthFeature6: "Feedback & communication", sectorHealthLink: "Healthcare solutions",
    contactKicker: "The next step", contactTitle: "Think digitally.<br>Delight guests.", contactText: "Let’s talk about your infrastructure, your guests and your goals.", footerClaim: "Your partner for digital hotel infrastructure.", footerSolutions: "Solutions", footerContact: "Contact", footerLegal: "Legal", rights: "All rights reserved.", footerTagline: "Proud to serve you.", backTop: "Back to top", imprint: "Legal notice", privacy: "Privacy", cookies: "Cookie policy"
  },
  fr: {
    navOverview: "Aperçu", navSolutions: "Solutions", navPlatform: "Plateforme", navContact: "Contact", contactCta: "Nous contacter",
    heroEyebrow: "Solutions digitales pour hôtels modernes", heroTitle: "Infrastructure digitale.<br>L’hospitalité réinventée.",
    heroLead: "Hotelinnovativ est votre partenaire pour des solutions digitales et une infrastructure hôtelière moderne.", discoverWorlds: "Découvrir les solutions", talkToUs: "Parlons-en", heroFootLeft: "Une plateforme. Deux univers d’expérience.", scroll: "Défiler",
    introKicker: "L’expérience hôtelière digitale", introTitle: "Une technologie discrète. Un impact que chaque hôte ressent.", introText: "Du premier contact à la chaîne préférée en chambre, nous relions services digitaux, divertissement et infrastructure dans une expérience cohérente.",
    journeyKicker: "Guest Journey", journeyTitle: "Chaque point de contact.<br>Une expérience.", journeyText: "Un parcours digital qui commence avant l’arrivée, simplifie le séjour et reste en mémoire après le départ.", journeyFeature1: "Pré-arrivée & upselling", journeyFeature2: "Clé mobile & Guest App", journeyFeature3: "Check-out & fidélisation", openJourney: "Vivre la Guest Journey",
    streamsKicker: "TV-Streams", streamsTitle: "Le monde comme invité.<br>Sur chaque écran.", streamsText: "La télévision internationale sur IP – flexible, centralisée et adaptée à votre clientèle.", streamsFeature1: "250+ chaînes internationales", streamsFeature2: "Bouquets flexibles", streamsFeature3: "Support suisse", openStreams: "Découvrir TV-Streams", tvWelcome: "Votre monde.<br>Votre programme.",
    platformKicker: "Infrastructure hôtelière connectée", platformTitle: "Un partenaire.<br>Un écosystème digital.", platformText: "Nous ne pensons pas en produits isolés, mais en solutions qui fonctionnent ensemble.", ecosystemCore: "CŒUR DIGITAL", ecoGuestApp: "Guest App", ecoAutomation: "Automatisation",
    serviceKicker: "Service & support", serviceTitle: "Ancrés localement.<br>À vos côtés personnellement.", serviceLead: "De la première idée à l’exploitation quotidienne, Hotelinnovativ reste à vos côtés – avec des circuits courts, une responsabilité directe et une équipe en Suisse.", swissLabel: "Votre partenaire technologique suisse", swissPromise: "Proche, rapide et fiable.", swissText: "Des interlocuteurs personnels à Baar, un accompagnement de projet expérimenté et un support qui connaît votre infrastructure.", serviceConsulting: "Conseil & conception", serviceConsultingText: "Nous transformons vos exigences en une solution claire et pérenne, adaptée à votre établissement, vos hôtes et vos opérations.", serviceIntegration: "Intégration & mise en service", serviceIntegrationText: "Une planification précise, une installation coordonnée et une intégration fiable dans l’infrastructure existante.", serviceSupport: "Support & évolution", serviceSupportText: "Une aide directe, des temps de réponse courts et une optimisation continue sur tout le cycle de vie.",
    audienceKicker: "Nos secteurs", audienceTitle: "Des expériences digitales pour les hôtels et les établissements de santé.", audienceLead: "Là où les personnes arrivent, séjournent et doivent se sentir bien accompagnées, Hotelinnovativ crée la connexion digitale.", sectorHotelLabel: "Hôtellerie", sectorHotelTitle: "Plus de confort pour les hôtes.<br>Plus d’impact pour les hôtels.", sectorHotelText: "Guest Journey, IPTV, casting, WiFi et automatisation s’unissent pour un séjour cohérent et des opérations plus efficaces.", sectorHotelLink: "Solutions pour les hôtels", sectorHealthLabel: "Établissements de santé", sectorHealthTitle: "TV patient interactive.<br>Information, confort et connexion.", sectorHealthText: "Le téléviseur existant devient une plateforme centrale qui informe, divertit et responsabilise les patients, tandis que les flux digitaux soutiennent les équipes soignantes.", healthFeature1: "TV & divertissement", healthFeature2: "Information & éducation", healthFeature3: "Repas & services", healthFeature4: "Contrôle de la chambre", healthFeature5: "Télésanté & famille", healthFeature6: "Feedback & communication", sectorHealthLink: "Solutions pour la santé",
    contactKicker: "La prochaine étape", contactTitle: "Penser digital.<br>Enchanter les hôtes.", contactText: "Parlons de votre infrastructure, de vos hôtes et de vos objectifs.", footerClaim: "Votre partenaire pour l’infrastructure hôtelière digitale.", footerSolutions: "Solutions", footerContact: "Contact", footerLegal: "Informations légales", rights: "Tous droits réservés.", footerTagline: "Proud to serve you.", backTop: "Haut de page", imprint: "Mentions légales", privacy: "Protection des données", cookies: "Politique des cookies"
  },
  it: {
    navOverview: "Panoramica", navSolutions: "Soluzioni", navPlatform: "Piattaforma", navContact: "Contatto", contactCta: "Contattaci",
    heroEyebrow: "Soluzioni digitali per hotel moderni", heroTitle: "Infrastruttura digitale.<br>Ospitalità ripensata.",
    heroLead: "Hotelinnovativ è il partner per soluzioni digitali e un’infrastruttura alberghiera moderna.", discoverWorlds: "Scopri le soluzioni", talkToUs: "Parliamone", heroFootLeft: "Una piattaforma. Due mondi di esperienza.", scroll: "Scorri",
    introKicker: "L’esperienza alberghiera digitale", introTitle: "Tecnologia che lavora dietro le quinte. Un impatto che l’ospite percepisce.", introText: "Dal primo contatto al canale preferito in camera, uniamo servizi digitali, intrattenimento e infrastruttura in un’esperienza coerente.",
    journeyKicker: "Guest Journey", journeyTitle: "Ogni touchpoint.<br>Un’esperienza.", journeyText: "Un percorso digitale che inizia prima dell’arrivo, semplifica il soggiorno e resta nel ricordo dopo la partenza.", journeyFeature1: "Pre-arrivo & upselling", journeyFeature2: "Mobile Key & Guest App", journeyFeature3: "Check-out & loyalty", openJourney: "Vivi la Guest Journey",
    streamsKicker: "TV-Streams", streamsTitle: "Il mondo come ospite.<br>Su ogni schermo.", streamsText: "Intrattenimento TV internazionale via IP – flessibile, gestito centralmente e adatto ai vostri ospiti.", streamsFeature1: "250+ canali internazionali", streamsFeature2: "Pacchetti flessibili", streamsFeature3: "Supporto svizzero", openStreams: "Scopri TV-Streams", tvWelcome: "Il tuo mondo.<br>Il tuo programma.",
    platformKicker: "Infrastruttura alberghiera connessa", platformTitle: "Un partner.<br>Un ecosistema digitale.", platformText: "Non pensiamo a prodotti isolati, ma a soluzioni che lavorano insieme.", ecosystemCore: "CUORE DIGITALE", ecoGuestApp: "Guest App", ecoAutomation: "Automazione",
    serviceKicker: "Service & support", serviceTitle: "Radicati localmente.<br>Al vostro fianco personalmente.", serviceLead: "Dalla prima idea alla gestione quotidiana, Hotelinnovativ resta al vostro fianco – con percorsi brevi, responsabilità diretta e un team in Svizzera.", swissLabel: "Il vostro partner tecnologico svizzero", swissPromise: "Vicino, rapido e affidabile.", swissText: "Referenti personali a Baar, una solida assistenza di progetto e un supporto che conosce la vostra infrastruttura.", serviceConsulting: "Consulenza & progettazione", serviceConsultingText: "Trasformiamo le esigenze in una soluzione chiara e pronta per il futuro, adatta alla struttura, agli ospiti e alla gestione.", serviceIntegration: "Integrazione & messa in servizio", serviceIntegrationText: "Pianificazione accurata, installazione coordinata e integrazione affidabile nell’infrastruttura esistente.", serviceSupport: "Supporto & sviluppo", serviceSupportText: "Assistenza diretta, tempi di risposta brevi e ottimizzazione continua durante l’intero ciclo di vita.",
    audienceKicker: "I nostri settori", audienceTitle: "Esperienze digitali per hotel e strutture sanitarie.", audienceLead: "Dove le persone arrivano, soggiornano e devono sentirsi ben assistite, Hotelinnovativ crea la connessione digitale.", sectorHotelLabel: "Hotellerie", sectorHotelTitle: "Più comfort per gli ospiti.<br>Più valore per gli hotel.", sectorHotelText: "Guest Journey, IPTV, casting, WiFi e automazione si uniscono per un soggiorno coerente e processi più efficienti.", sectorHotelLink: "Soluzioni per hotel", sectorHealthLabel: "Strutture sanitarie", sectorHealthTitle: "TV interattiva per i pazienti.<br>Informazione, comfort e connessione.", sectorHealthText: "Il televisore esistente diventa una piattaforma centrale che informa, intrattiene e responsabilizza i pazienti, mentre i flussi digitali supportano il personale sanitario.", healthFeature1: "TV & intrattenimento", healthFeature2: "Informazione & formazione", healthFeature3: "Pasti & servizi", healthFeature4: "Controllo camera", healthFeature5: "Telemedicina & famiglia", healthFeature6: "Feedback & comunicazione", sectorHealthLink: "Soluzioni per la sanità",
    contactKicker: "Il prossimo passo", contactTitle: "Pensare digitale.<br>Entusiasmare gli ospiti.", contactText: "Parliamo della vostra infrastruttura, dei vostri ospiti e dei vostri obiettivi.", footerClaim: "Il vostro partner per l’infrastruttura alberghiera digitale.", footerSolutions: "Soluzioni", footerContact: "Contatto", footerLegal: "Note legali", rights: "Tutti i diritti riservati.", footerTagline: "Proud to serve you.", backTop: "Torna su", imprint: "Note legali", privacy: "Protezione dei dati", cookies: "Politica dei cookie"
  }
};

const allowedLanguages = Object.keys(translations);
const languageButtons = document.querySelectorAll("[data-lang]");

function setLanguage(language) {
  const lang = allowedLanguages.includes(language) ? language : "de";
  const dictionary = translations[lang];
  document.documentElement.lang = lang === "de" ? "de-CH" : lang;
  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const value = dictionary[element.dataset.i18n];
    if (value) element.innerHTML = value;
  });
  languageButtons.forEach((button) => button.classList.toggle("active", button.dataset.lang === lang));
  const url = new URL(window.location.href);
  url.searchParams.set("lang", lang);
  history.replaceState({}, "", url);
  localStorage.setItem("hi-language", lang);
}

languageButtons.forEach((button) => button.addEventListener("click", () => setLanguage(button.dataset.lang)));

const preferredLanguage = new URLSearchParams(location.search).get("lang") || localStorage.getItem("hi-language") || navigator.language.slice(0, 2);
setLanguage(preferredLanguage);

const revealObserver = new IntersectionObserver((entries) => {
  entries.forEach((entry) => {
    if (entry.isIntersecting) {
      entry.target.classList.add("visible");
      revealObserver.unobserve(entry.target);
    }
  });
}, { threshold: 0.14 });

document.querySelectorAll(".reveal").forEach((element) => revealObserver.observe(element));

function updateScrollState() {
  const scrollable = document.documentElement.scrollHeight - innerHeight;
  const ratio = scrollable > 0 ? scrollY / scrollable : 0;
  document.getElementById("progress").style.width = `${ratio * 100}%`;
  document.getElementById("header").classList.toggle("scrolled", scrollY > 45);
  document.documentElement.style.setProperty("--scroll-shift", `${Math.min(scrollY * 0.06, 45)}px`);
}

addEventListener("scroll", updateScrollState, { passive: true });
updateScrollState();
document.getElementById("year").textContent = new Date().getFullYear();
